baseURL = "/"
languageCode = "en-us"
title = "ito"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "ito App is a application to track infections."
    meta_og_title = "ito App"
    meta_og_type = "website"
    meta_og_url = "https://ito-app.org"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "ito App is a tracking app to track contacts without tracking the people. It is completly anonyme and no personal data is needet to use ito."
    meta_twitter_card = "summary"
    meta_twitter_site = "@bandemicapp"
    meta_twitter_creator = "@bandemicapp"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
