baseURL = "/"
languageCode = "en-us"
title = "ito | Track infections, not people"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "About"
url     = "about"
weight  = 2
#[[menu.main]]
#name    = "Service"
#url     = "service"
#weight  = 3
#[[menu.main]]
#name    = "Gallery"
#url     = "gallery"
#weight  = 4
[[menu.main]]
name    = "Blog"
url     = "blog"
weight  = 5
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 6

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "ito means"
description = "Track infections, not people!"
# button
btn     = true
btnText = "Download Now"
btnURL  = "https://github.com/ito-org/react-native-app"

# flip text
[[params.banner.flipText]]
title   = "Infection Termination Operation"
[[params.banner.flipText]]
title   = "Integrated thermodynamic obscurity"
[[params.banner.flipText]]
title   = "Infection Tracking Opportunity"
[[params.banner.flipText]]
title   = "\"Thread\" in Japanese"

# Homepage About Section
[params.about]
enable  = true
title   = "ito has battled pathogens before it was cool"
content = "Emerged as part of a grassroots initiative in March 2020, ito is an application for tracking infections using smart devices with Bluetooth technology."
image   = "images/about/about.jpg"

# Call to Action
[params.cta]
enable  = true
title   = "We work 100% transparently?"
content = "ito is made by regular people just like you. We want to help the world stay safe and we mean it. That's why we open source every part of our work."
btnText = "Talk to us"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = false
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "https://www.instagram.com/bandemic.app/"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"
